//! Proof-store helpers that dispatch on [`ProofId`] variants.
//!
//! These free functions encapsulate the match-on-ProofId pattern, keeping the
//! orchestrator focused on coordination logic. They operate through the
//! [`ProofDb`] surface of the [`ProverContext`].

use std::fmt;

use strata_asm_prover_types::{AsmProof, MohoProof, ProofId};
use tracing::info;
use zkaleido::ProofReceiptWithMetadata;

use crate::{
    ProverContext,
    errors::{ProverError, ProverResult},
};

/// Returns `true` if the proof already exists in the local proof store.
pub(crate) async fn proof_exists<C: ProverContext>(
    ctx: &C,
    proof_id: &ProofId,
) -> ProverResult<bool> {
    match proof_id {
        ProofId::Asm(range) => {
            let exists = ctx
                .get_asm_proof(*range)
                .await
                .map_err(|e| ProverError::storage("failed to check ASM proof", e))?
                .is_some();
            Ok(exists)
        }
        ProofId::Moho(commitment) => {
            let exists = ctx
                .get_moho_proof(*commitment)
                .await
                .map_err(|e| ProverError::storage("failed to check Moho proof", e))?
                .is_some();
            Ok(exists)
        }
    }
}

/// Where a completed proof receipt came from.
///
/// Receipts from both sources are expected to be equivalent; the distinction
/// exists so the store log attributes each proof to the path that produced
/// it.
#[derive(Debug, Clone, Copy)]
pub(crate) enum ProofSource {
    /// Generated by the local proving backend.
    Backend,
    /// Fetched from the follower's peer.
    Peer,
}

impl fmt::Display for ProofSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Backend => f.write_str("backend"),
            Self::Peer => f.write_str("peer"),
        }
    }
}

/// Stores a completed proof receipt in the appropriate proof-store table.
pub(crate) async fn store_completed_proof<C: ProverContext>(
    ctx: &C,
    proof_id: ProofId,
    receipt: ProofReceiptWithMetadata,
    source: ProofSource,
) -> ProverResult<()> {
    match proof_id {
        ProofId::Asm(range) => {
            info!(?range, %source, "storing completed ASM proof");
            ctx.store_asm_proof(range, AsmProof(receipt))
                .await
                .map_err(|e| ProverError::storage("failed to store ASM proof", e))?;
        }
        ProofId::Moho(commitment) => {
            info!(?commitment, %source, "storing completed Moho proof");
            ctx.store_moho_proof(commitment, MohoProof(receipt))
                .await
                .map_err(|e| ProverError::storage("failed to store Moho proof", e))?;
        }
    }
    Ok(())
}
