#[cfg(feature = "arbitrary")]
use arbitrary::Arbitrary;
use ssz_types::VariableList;
use strata_crypto::hash;
use strata_identifiers::{L1_HEIGHT_MMR_PREFILL_LEAF, L1BlockId, L1Height, WtxidsRoot};
use tree_hash::{Sha256Hasher, TreeHash};

use crate::{
    AsmManifestError, AsmManifestHash, AsmManifestRangeHash, AsmManifestResult,
    ssz_generated::ssz::{log::AsmLogEntry, manifest::AsmManifest},
};

/// We could potentially have a different prefill value for ASM manifest MMR.
/// So defining a separate constant. The prefill value can be changed if necessary.
pub const ASM_MANIFEST_MMR_PREFILL_LEAF: [u8; 32] = L1_HEIGHT_MMR_PREFILL_LEAF;

impl AsmManifest {
    /// Creates a new ASM manifest.
    ///
    /// Returns [`AsmManifestError::TooManyLogs`] if `logs` exceeds the SSZ
    /// capacity for the manifest's `logs` field.
    pub fn new(
        height: L1Height,
        blkid: L1BlockId,
        wtxids_root: WtxidsRoot,
        logs: Vec<AsmLogEntry>,
    ) -> AsmManifestResult<Self> {
        let logs = VariableList::new(logs).map_err(AsmManifestError::TooManyLogs)?;
        Ok(Self {
            height,
            blkid,
            wtxids_root,
            logs,
        })
    }

    /// Returns the L1 block height.
    pub fn height(&self) -> L1Height {
        self.height
    }

    /// Returns the L1 block identifier.
    pub fn blkid(&self) -> &L1BlockId {
        &self.blkid
    }

    /// Returns the witness transaction ID merkle root.
    pub fn wtxids_root(&self) -> &WtxidsRoot {
        &self.wtxids_root
    }

    /// Returns the log entries.
    pub fn logs(&self) -> &[AsmLogEntry] {
        &self.logs
    }

    /// Computes the hash of the manifest using SSZ tree hash.
    ///
    /// This uses SSZ to compute the root of the `AsmManifest` container, which
    /// enables creating Merkle inclusion proofs for individual fields (logs,
    /// `wtxids_root`, etc.) when needed.
    pub fn compute_hash(&self) -> AsmManifestHash {
        let root = TreeHash::tree_hash_root::<Sha256Hasher>(self);
        AsmManifestHash::from(root.0)
    }
}

// Manual Arbitrary implementation for testing/benchmarking
#[cfg(feature = "arbitrary")]
impl<'a> Arbitrary<'a> for AsmManifest {
    fn arbitrary(u: &mut arbitrary::Unstructured<'a>) -> arbitrary::Result<Self> {
        let height = u32::arbitrary(u)?;
        let blkid = L1BlockId::arbitrary(u)?;
        let wtxids_root = WtxidsRoot::arbitrary(u)?;

        // Generate a small number of logs for testing
        let num_logs = u.int_in_range(0..=10)?;
        let mut logs = Vec::with_capacity(num_logs);
        for _ in 0..num_logs {
            logs.push(AsmLogEntry::arbitrary(u)?);
        }

        AsmManifest::new(height, blkid, wtxids_root, logs)
            .map_err(|_| arbitrary::Error::IncorrectFormat)
    }
}

/// Computes a commitment hash over a sequence of ASM manifests.
///
/// Hashes each manifest individually via [`AsmManifest::compute_hash`] and
/// delegates to [`compute_asm_manifests_hash_from_leaves`].
///
/// Returns the zero hash when `manifests` is empty.
pub fn compute_asm_manifests_hash(manifests: &[AsmManifest]) -> AsmManifestRangeHash {
    let leaves: Vec<AsmManifestHash> = manifests.iter().map(AsmManifest::compute_hash).collect();
    compute_asm_manifests_hash_from_leaves(&leaves)
}

/// Computes a commitment hash over pre-hashed ASM manifest leaves.
///
/// This is the low-level counterpart of [`compute_asm_manifests_hash`] for
/// callers that already have individual manifest hashes (e.g. from auxiliary
/// data).
///
/// Returns [`AsmManifestRangeHash::ZERO`] when `leaves` is empty.
pub fn compute_asm_manifests_hash_from_leaves(leaves: &[AsmManifestHash]) -> AsmManifestRangeHash {
    if leaves.is_empty() {
        return AsmManifestRangeHash::ZERO;
    }
    let buf = hash::sha256_iter(leaves.iter().map(|h| h.as_ref() as &[u8]));
    AsmManifestRangeHash::from(buf)
}

#[cfg(test)]
mod tests {
    use proptest::prelude::*;
    use ssz::{Decode, Encode};
    use strata_identifiers::{
        Buf32, L1BlockId, WtxidsRoot,
        test_utils::{buf32_strategy, l1_block_id_strategy},
    };
    use strata_ssz_tests::ssz_proptest;

    use super::AsmManifest;
    use crate::ssz_generated::ssz::log::AsmLogEntry;

    /// Expectations generated by the production codec at v0.3.0-rc.2 / 45a1fa2.
    #[test]
    fn baseline_manifest_bytes_and_roots_are_unchanged() {
        let vectors = [
            (
                0,
                include_bytes!("../test-data/baseline/manifest-0.ssz").as_slice(),
                [
                    0x1b, 0x16, 0x3b, 0xf0, 0x15, 0xf5, 0x5a, 0x3f, 0x1f, 0xc0, 0x46, 0x97, 0x6a,
                    0xa2, 0x41, 0x6d, 0x27, 0x3b, 0xda, 0xf6, 0x74, 0x81, 0xe2, 0x26, 0xf5, 0xc2,
                    0xb8, 0xb5, 0x44, 0x11, 0xc7, 0xba,
                ],
            ),
            (
                1,
                include_bytes!("../test-data/baseline/manifest-1.ssz").as_slice(),
                [
                    0xd7, 0xd3, 0x86, 0xbc, 0x28, 0x34, 0xca, 0x5b, 0x54, 0x92, 0xd8, 0xa6, 0x0b,
                    0x1d, 0xfc, 0x81, 0x8d, 0x84, 0xf0, 0x79, 0x6f, 0x09, 0x13, 0xcc, 0xc6, 0xe0,
                    0x13, 0xc8, 0x17, 0x87, 0x15, 0xac,
                ],
            ),
            (
                2,
                include_bytes!("../test-data/baseline/manifest-2.ssz").as_slice(),
                [
                    0x5f, 0xe0, 0x2f, 0x58, 0x10, 0xac, 0xf4, 0x4b, 0x8e, 0x99, 0x03, 0x4a, 0x0e,
                    0x3c, 0xe6, 0xcf, 0x53, 0x01, 0x89, 0x21, 0x12, 0xf0, 0x2c, 0xc6, 0x4b, 0xb2,
                    0xf1, 0x98, 0x48, 0x59, 0x03, 0x89,
                ],
            ),
            (
                1024,
                include_bytes!("../test-data/baseline/manifest-1024.ssz").as_slice(),
                [
                    0x68, 0xeb, 0x89, 0x06, 0xa2, 0x27, 0x72, 0x07, 0x25, 0x6c, 0x1b, 0xeb, 0x9d,
                    0x47, 0xea, 0x86, 0xc2, 0xe3, 0xaa, 0x08, 0xe2, 0x84, 0x11, 0xfe, 0x0b, 0xfc,
                    0x55, 0xdc, 0x95, 0x04, 0xdf, 0xba,
                ],
            ),
        ];
        for (count, encoded, expected_root) in vectors {
            let logs = (0..count)
                .map(|i| AsmLogEntry::from_raw(vec![i as u8, 2, 3]).unwrap())
                .collect();
            let manifest = AsmManifest::new(
                100,
                L1BlockId::from(Buf32::from([0x11; 32])),
                WtxidsRoot::from(Buf32::from([0x22; 32])),
                logs,
            )
            .unwrap();
            assert_eq!(
                manifest.as_ssz_bytes(),
                encoded,
                "baseline encoding, {count} logs"
            );
            assert_eq!(
                manifest.compute_hash(),
                crate::AsmManifestHash::from(expected_root),
                "baseline root, {count} logs"
            );
            assert_eq!(AsmManifest::from_ssz_bytes(encoded).unwrap(), manifest);
            let mut altered = encoded.to_vec();
            altered[4] ^= 1;
            assert_ne!(
                AsmManifest::from_ssz_bytes(&altered)
                    .unwrap()
                    .compute_hash(),
                manifest.compute_hash()
            );
        }
    }

    #[test]
    fn baseline_capacity_rejects_1025_logs_in_construction_and_decoding() {
        let log = AsmLogEntry::from_raw(vec![0, 2, 3]).unwrap();
        assert!(matches!(
            AsmManifest::new(
                100,
                L1BlockId::from(Buf32::from([0x11; 32])),
                WtxidsRoot::from(Buf32::from([0x22; 32])),
                vec![log.clone(); 1025]
            ),
            Err(crate::AsmManifestError::TooManyLogs(_))
        ));
        // Encode an oversized list manually so decoder coverage cannot be bypassed
        // by the constructor's independent bound check.
        let mut encoded = include_bytes!("../test-data/baseline/manifest-0.ssz").to_vec();
        for i in 0..1025u32 {
            encoded.extend_from_slice(&(1025 * 4 + i * 7).to_le_bytes());
        }
        for _ in 0..1025 {
            encoded.extend_from_slice(&log.as_ssz_bytes());
        }
        assert!(AsmManifest::from_ssz_bytes(&encoded).is_err());
    }

    fn wtxids_root_strategy() -> impl Strategy<Value = WtxidsRoot> {
        buf32_strategy().prop_map(WtxidsRoot::from)
    }

    fn asm_log_entry_strategy() -> impl Strategy<Value = AsmLogEntry> {
        prop::collection::vec(any::<u8>(), 0..256)
            .prop_map(|bytes| AsmLogEntry::from_raw(bytes).expect("bytes within capacity"))
    }

    fn asm_manifest_strategy() -> impl Strategy<Value = AsmManifest> {
        (
            any::<u32>(),
            l1_block_id_strategy(),
            wtxids_root_strategy(),
            prop::collection::vec(asm_log_entry_strategy(), 0..10),
        )
            .prop_map(|(height, blkid, wtxids_root, logs)| {
                AsmManifest::new(height, blkid, wtxids_root, logs).expect("logs within capacity")
            })
    }

    mod asm_manifest {
        use super::*;

        ssz_proptest!(AsmManifest, asm_manifest_strategy());

        #[test]
        fn test_empty_logs() {
            let manifest = AsmManifest::new(
                100,
                L1BlockId::from(Buf32::from([0u8; 32])),
                WtxidsRoot::from(Buf32::from([1u8; 32])),
                vec![],
            )
            .unwrap();
            let encoded = manifest.as_ssz_bytes();
            let decoded = AsmManifest::from_ssz_bytes(&encoded).unwrap();
            assert_eq!(manifest.height(), decoded.height());
            assert_eq!(manifest.blkid(), decoded.blkid());
            assert_eq!(manifest.wtxids_root(), decoded.wtxids_root());
            assert_eq!(manifest.logs().len(), decoded.logs().len());
        }

        #[test]
        fn test_with_logs() {
            let logs = vec![
                AsmLogEntry::from_raw(vec![1, 2, 3]).unwrap(),
                AsmLogEntry::from_raw(vec![4, 5, 6]).unwrap(),
            ];
            let manifest = AsmManifest::new(
                200,
                L1BlockId::from(Buf32::from([0u8; 32])),
                WtxidsRoot::from(Buf32::from([1u8; 32])),
                logs.clone(),
            )
            .unwrap();
            let encoded = manifest.as_ssz_bytes();
            let decoded = AsmManifest::from_ssz_bytes(&encoded).unwrap();
            assert_eq!(manifest.height(), decoded.height());
            assert_eq!(manifest.logs().len(), decoded.logs().len());
            for (original, decoded_log) in manifest.logs().iter().zip(decoded.logs()) {
                assert_eq!(original.as_bytes(), decoded_log.as_bytes());
            }
        }

        #[test]
        fn test_compute_hash_deterministic() {
            let manifest = AsmManifest::new(
                100,
                L1BlockId::from(Buf32::from([0u8; 32])),
                WtxidsRoot::from(Buf32::from([1u8; 32])),
                vec![AsmLogEntry::from_raw(vec![1, 2, 3]).unwrap()],
            )
            .unwrap();
            let hash1 = manifest.compute_hash();
            let hash2 = manifest.compute_hash();
            assert_eq!(hash1, hash2);
        }

        #[test]
        fn test_compute_hash_different_for_different_manifests() {
            let manifest1 = AsmManifest::new(
                100,
                L1BlockId::from(Buf32::from([0u8; 32])),
                WtxidsRoot::from(Buf32::from([1u8; 32])),
                vec![AsmLogEntry::from_raw(vec![1, 2, 3]).unwrap()],
            )
            .unwrap();
            let manifest2 = AsmManifest::new(
                100,
                L1BlockId::from(Buf32::from([1u8; 32])),
                WtxidsRoot::from(Buf32::from([1u8; 32])),
                vec![AsmLogEntry::from_raw(vec![1, 2, 3]).unwrap()],
            )
            .unwrap();
            let hash1 = manifest1.compute_hash();
            let hash2 = manifest2.compute_hash();
            assert_ne!(hash1, hash2);
        }
    }
}
