[package]
name = "strata-asm-params"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-admin-types.workspace = true
strata-asm-proto-bridge-types.workspace = true
strata-asm-proto-checkpoint-types.workspace = true
strata-btc-verification.workspace = true
strata-identifiers = { workspace = true, optional = true }
strata-l1-txfmt.workspace = true

arbitrary = { workspace = true, optional = true }
bitcoin = { workspace = true, optional = true }
serde.workspace = true

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true

[features]
arbitrary = [
  "dep:arbitrary",
  "dep:bitcoin",
  "dep:strata-identifiers",
  "strata-asm-admin-types/arbitrary",
  "strata-asm-proto-bridge-types/arbitrary",
  "strata-asm-proto-checkpoint-types/arbitrary",
]
