[package]
edition = "2024"
name = "strata-asm-rpc"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
strata-asm-bridge-types.workspace = true
strata-asm-checkpoint-types.workspace = true
strata-asm-common.workspace = true
strata-asm-params.workspace = true
strata-asm-proto-bridge.workspace = true
strata-asm-prover-types.workspace = true
strata-asm-worker.workspace = true

bitcoin.workspace = true
jsonrpsee = { workspace = true, features = ["server", "macros"] }

[features]
default = []
client = ["jsonrpsee/client"]
